apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: restaurantspace
spec:
  selector:
    app: restaurant-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
